### ISSUE TITLE
Permissions errors are a bit opaque

### ISSUE THREAD

**Issue by jchesterpivotal** [dpb587/github-status-resource#7]
I got stumped by this:

    FATAL: Status not found on [git sha]

Superficially this looks like #3, but it wasn't. The problem was that the relevant bot didn't have write access to the relevant repository.

It would be good if 
* the docs outlined the starting position of having write access, as well as the existing note on token scope
* the code sniffed out permissions errors and told you about them.

**Comment by dpb587** [comment]
When you say didn’t have “write” access, which permissions did you find were required?

It should only require the “repo:status” scope documented in the readme and not need full write permissions to a repo.

**Comment by jchesterpivotal** [comment]
The bot in question was a collaborator on the repo. When configured as having "Read" permission, I get the "FATAL" above. With "Write" it works.

This is distinct from the token scope; it's a permission set on the user.

**Comment by dpb587** [comment]
Ah, I see. That makes sense then, thanks.

Probably should update the readme with the note and tweak the fatal error
message with a hint.

**Comment by dpb587** [comment]
Code to sniff out permission errors doesn't look very practical, so I've updated the readme with a note. Hopefully between that note and this issue being searchable, people won't struggle for too long on similar issues.
